name: perpustakaan_teknokrat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_auth: ^4.15.0
  google_sign_in: ^6.1.6
  cloud_firestore: ^4.13.3
  firebase_database: ^10.3.6
  random_string: ^2.3.1
  carousel_slider: ^4.2.1
  marquee: ^2.2.3
  firebase_storage: ^11.5.3
  image_picker: ^1.0.4
  pdfx: ^2.5.0
  file_picker: ^6.1.1
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.1
  syncfusion_flutter_pdfviewer: ^23.2.7

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
      - assets/images/
      - assets/images/vectorauth2.png
      - assets/images/vectorauth.png

